### ISSUE TITLE
Add monitoring of AWS Cloud

### ISSUE THREAD

**Issue by matthi-g** [Apollo-Tools/resource-manager#18]
- [x] Check if cloud is reachable
- [x] Check latency to cloud regions (e.g. use [this](https://aws-latency-test.com/)
- [x] Use AWS price list api to get current pricings

**Comment by stefanpedratscher** [comment]
Hi @matthi-g , thank you for creating.

I am currently discussing with @zahranajaf 

We wrote in the agreement: 
```To keep track of these resources it is necessary to implement a monitoring service that observes metrics like the online state, utilization (memory, cpu and disc), costs, energy consumption, co2 emissions, latency, bandwidth and others.  Based on these metrics and the SLOs that are set by the client, resources are proposed that can then be reserved by the client.```

What about these functionalities? Do we get them e.g. for EC2/openFaaS?

**Comment by stefanpedratscher** [comment]
Yes, this sounds not that bad. What do you think @zahranajaf ?

**Comment by matthi-g** [comment]
Monitoring of latency, up status and price list is implemented through a custom solution in vertx. Metrics regarding ec2 resources are exposed with node exporter and scraped by victoria metrics
